Z9TheCoffee/Z9TheCoffee/Controllers/QuanLy_Z9TheCoffeeController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Z9TheCoffee.Models;

namespace Z9TheCoffee.Controllers
{
    public class QuanLy_Z9TheCoffeeController : Controller
    {
        // GET: NguoiDung    
        DataClasses1DataContext data = new DataClasses1DataContext();

        public ActionResult DangNhap(FormCollection collection)
        {
            var taikhoan = collection["TaiKhoan"];
            var matkhau = collection["MatKhau"];
            if (String.IsNullOrEmpty(taikhoan) || String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi1"] = "* Bắt buộc";
            }
            else
            {
                MayChu ad = data.MayChus.SingleOrDefault(n => n.TaiKhoan_admin == taikhoan && n.MatKhau_admin == matkhau);
                if (ad != null)
                {
                    Session["TenAdmin"] = ad.TaiKhoan_admin;
                    return RedirectToAction("Index", "QuanLy_Z9TheCoffee");
                }
                else
                {
                    ViewBag.ThongBao = "* Tên đăng nhập hoặc mật khẩu không đúng";
                }
            }
            return View();
        }
        public ActionResult Index()
        {
            if (Session["TenAdmin"] == null || Session["TenAdmin"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "QuanLy_Z9TheCoffee");
            }
            else
            {
                return View();
            }
        }
        // đăng xuất
        public ActionResult DangXuat()
        {
            Session["TenAdmin"] = null;
            return RedirectToAction("Index", "QuanLy_Z9TheCoffee");
        }
        public List<listMenu> listQuanLy_Menu()
        {
            var listQuanLy_Menu = from du in data.ChiTietDoUongs
                                  from tl in data.LoaiDoUongs
                                  where du.MaLoai == tl.MaLoai
                                  select new listMenu()
                                  {
                                      NgayCapNhat = Convert.ToDateTime(du.NgayCapNhat),
                                      TenLoai = tl.TenLoai,
                                      MaDoUong = du.MaDoUong,
                                      TenDoUong = du.TenDoUong,
                                      GiaBan = Convert.ToDecimal(du.GiaBan),
                                      AnhBia = du.AnhBia,
                                      TrangThai = Convert.ToBoolean(du.TrangThai)
                                  };
            return listQuanLy_Menu.OrderBy(a => a.NgayCapNhat).ToList();
        }
        public ActionResult Menu(int? page)
        {
            if (Session["TenAdmin"] == null || Session["TenAdmin"].ToString() == "")
            {
                return RedirectToAction("Index", "QuanLy_Z9TheCoffee");
            }
            var laydanhsach = listQuanLy_Menu();
            int pageNumber = (page ?? 1);
            int pageSize = 20;
            return View(laydanhsach.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult DanhSachChiNhanh()
        {
            if (Session["TenAdmin"] == null || Session["TenAdmin"].ToString() == "")
            {
                return RedirectToAction("Index", "QuanLy_Z9TheCoffee");
            }
            List<ChiNhanh> chiNhanhs = data.ChiNhanhs.Where(v => v.TrangThai != false).ToList();
            return View(chiNhanhs);
        }
        public ActionResult CapNhatMenu(int id)
        {
            if (Session["TenAdmin"] == null || Session["TenAdmin"].ToString() == "")
            {
                return RedirectToAction("Index", "QuanLy_Z9TheCoffee");
            }
            else
            { //Lay ra doi tuong sach theo ma                                              
                ViewBag.MaLoai = new SelectList(data.LoaiDoUongs.Where(a => a.TrangThai == true).ToList(), "MaLoai", "TenLoai");
                ChiTietDoUong du = data.ChiTietDoUongs.SingleOrDefault(n => n.MaDoUong == id);
                du.NgayCapNhat = DateTime.Today;
                return View(du);
            }
        }
        public ActionResult SuaThongTinChiNhanh(int id)
        {
            if (Session["TenAdmin"] == null || Session["TenAdmin"].ToString() == "")
            {
                return RedirectToAction("Index", "QuanLy_Z9TheCoffee");
            }
            else
            {
                ViewBag.MaLoai = new SelectList(data.ChiNhanhs.Where(a => a.TrangThai == true)).ToList();
                ChiNhanh chiNhanh = data.ChiNhanhs.SingleOrDefault(n => n.MaChiNhanh == id);
                return View(chiNhanh);
            }
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SuaThongTinChiNhanh(FormCollection collection)
        {
            if (Session["TenAdmin"] == null || Session["TenAdmin"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "QuanLy_Z9TheCoffee");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        ChiNhanh chiNhanh = data.ChiNhanhs.Where(a => a.MaChiNhanh == Convert.ToInt32(collection["MaChiNhanh"])).FirstOrDefault();
                        chiNhanh.TenChiNhanh = Convert.ToString(collection["TenChiNhanh"]);
                        chiNhanh.TrangThai = Convert.ToBoolean(collection["TrangThai"]);
                        //data.ChiNhanhs.
                        data.SubmitChanges();
                    }

                    catch { ViewBag.Loi = "Vui lòng kiểm tra đầy đủ thông tin"; }


                }
            }
            return RedirectToAction("DanhSachChiNhanh", "QuanLy_Z9TheCoffee");
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CapNhatMenu(int id, FormCollection collection, ChiTietDoUong du, HttpPostedFileBase fileUpload)
        {
            if (Session["TenAdmin"] == null || Session["TenAdmin"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "QuanLy_Z9TheCoffee");
            }            
            else
            {               
                //Them vao CSDL               
                if (ModelState.IsValid)
                {
                    try
                    {
                        du = data.ChiTietDoUongs.SingleOrDefault(n => n.MaDoUong == id);
                        du.NgayCapNhat = Convert.ToDateTime(collection["NgayCapNhat"]);
                        du.MaLoai = Convert.ToInt32(collection["MaLoai"]);
                        du.TenDoUong = collection["TenDoUong"];
                        du.GiaBan = Convert.ToDecimal(collection["GiaBan"]);
                        //Luu ten fie, luu y bo sung thu vien using System.IO;
                        if (fileUpload != null)
                        {
                            var fileName = Path.GetFileName(fileUpload.FileName);
                            //Luu duong dan cua file
                            var path = Path.Combine(Server.MapPath("~/HinhSanPham"), fileName);
                            //Luu hinh anh vao duong dan
                            fileUpload.SaveAs(path);
                            du.AnhBia = fileName;
                        }
                        //else
                        //{
                        //    du.AnhBia = collection["AnhBia"];
                        //}
                        
                        du.TrangThai = Convert.ToBoolean(collection["TrangThai"]);
                        //Luu vao CSDL                             
                        data.SubmitChanges();
                    }
                    catch { ViewBag.Loi = "Vui lòng kiểm tra đầy đủ thông tin"; return null; }
                }
                return RedirectToAction("Menu", "QuanLy_Z9TheCoffee");
            }
        }
        public ActionResult ThemMoiMenu()
        {
            if (Session["TenAdmin"] == null || Session["TenAdmin"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "QuanLy_Z9TheCoffee");
            }
            ViewBag.MaLoai = new SelectList(data.LoaiDoUongs.Where(a => a.TrangThai == true).ToList(), "MaLoai", "TenLoai");
            return View();
        }
        public ActionResult ThemMoiChiNhanh()
        {
            if (Session["TenAdmin"] == null || Session["TenAdmin"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "QuanLy_Z9TheCoffee");
            }
            ViewBag.MaLoai = new SelectList(data.LoaiDoUongs.Where(a => a.TrangThai == true).ToList(), "MaLoai", "TenLoai");
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoiChiNhanh(FormCollection collection,ChiNhanh chiNhanh)
        {
            if (Session["TenAdmin"] == null || Session["TenAdmin"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "QuanLy_Z9TheCoffee");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    chiNhanh.TenChiNhanh = Convert.ToString(collection["TenChiNhanh"]);
                    chiNhanh.TrangThai = Convert.ToBoolean(collection["TrangThai"]);
                    data.ChiNhanhs.InsertOnSubmit(chiNhanh);
                    data.SubmitChanges();
                }
            }
            return RedirectToAction("DanhSachChiNhanh", "QuanLy_Z9TheCoffee");
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoiMenu(FormCollection collection, ChiTietDoUong du, HttpPostedFileBase fileUpload)
        {

            if (Session["TenAdmin"] == null || Session["TenAdmin"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "QuanLy_Z9TheCoffee");

Z9TheCoffee/Z9TheCoffee/Controllers/Z9TheCoffeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Z9TheCoffee.Models;

namespace Z9TheCoffee.Controllers
{
    public class Z9TheCoffeeController : Controller
    {
        // GET: TrangChu
        DataClasses1DataContext data = new DataClasses1DataContext();
        private List<ChiTietDoUong> Laydouongmoi(int count)
        {
            // sắp xếp giảm dần theo ngày cập nhật, lấy count dòng đầu
            var Laydouongmoi = from ctdu in data.ChiTietDoUongs where ctdu.TrangThai == true select ctdu;
            return Laydouongmoi.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
            //return data.ChiTietDoUongs.Where(a=> a.TrangThai()).OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }
        public ActionResult Index()
        {           
            var douongmoi = Laydouongmoi(100);           
            return View(douongmoi);
        }
        public ActionResult CaPheViet()
        {
            var capheviet = from cfviet in data.ChiTietDoUongs where cfviet.MaLoai == 1 && cfviet.TrangThai == true select cfviet;
            return PartialView(capheviet);
        }
        public ActionResult CaPheY()
        {
            var caphey = from cfy in data.ChiTietDoUongs where cfy.MaLoai == 2 && cfy.TrangThai == true select cfy;
            return PartialView(caphey);
        }
        public ActionResult Tra()
        {
            var tra = from t in data.ChiTietDoUongs where t.MaLoai == 3 && t.TrangThai == true select t;
            return PartialView(tra);
        }

    }
}

Z9TheCoffee/Z9TheCoffee/Views/QuanLy_Z9TheCoffee/CapNhatMenu.cshtml
@model Z9TheCoffee.Models.ChiTietDoUong

@{
    ViewBag.Title = "CapNhatMenu";
    Layout = "~/Views/Shared/_LayoutQuanLy.cshtml";
    }
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cập nhật Menu</title>
    <style>
        table {
            border-collapse: collapse;
            border-spacing: 0;
            width: 100%;
            border: 1px solid #ddd;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    @using (Html.BeginForm("CapNhatMenu", "QuanLy_Z9TheCoffee", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div style="overflow-x:auto;">
            <table style="border:solid;text-align:center" class="responsive wrap">
                <tr style="text-align:center; font-weight:bold;border:solid">
                    <td>Ngày Cập Nhật</td>
                    <td>Tên Loại</td>                  
                    <td>Tên Đồ Uống</td>
                    <td>Giá Bán</td>
                    <td>Ảnh Bìa</td>
                    <td>Trạng Thái</td>
                </tr>
                <tr style="text-align:center; font-weight:bold;border:solid">
                    <td style="border:solid;width:100px">                       
                        @Html.EditorFor(model => model.NgayCapNhat, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NgayCapNhat, "", new { @class = "text-danger" })
                    </td>
                    <td style="border:solid">@Html.DropDownList("MaLoai", ViewBag.MaLoai as SelectList)</td>                 
                    <td style="border:solid">
                        @Html.EditorFor(model => model.TenDoUong, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenDoUong, "", new { @class = "text-danger" })
                    </td>
                    <td style="border:solid;width:90px">
                        @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
                    </td>
                    <td style="border:solid;width:60px">                        
                        <p>Tên ảnh hiện tại: @Html.DisplayFor(model => model.AnhBia, new { htmlAttributes = new { @class = "form-control" } })</p>                                                                     
                        <img src="@Url.Content("~/HinhSanPham/" + Model.AnhBia)" width="120" /> (Ảnh Hiện Tại)
                        <input type="file" name="fileUpload" />
                    </td>
                    <td style="border:solid">
                        @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                    </td>
                </tr>
            </table><br />
            <div style="text-align: center"><button class="btn primary-btn" type="submit">Lưu</button></div>
        </div>
    }
</body>

Z9TheCoffee/Z9TheCoffee/Views/QuanLy_Z9TheCoffee/DangNhap.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Đăng Nhập</title>
    <link rel="shortcut icon" href="~/img/logo_website.png">
    <style>
        .wrap {
            width: 90%;
            margin: 0 auto;
            -moz-transition: all .2s linear;
            -webkit-transition: all .2s linear;
            -o-transition: all .2s linear;
        }
    </style>
</head>
<body style="background-image: url('../../img/header-bg.jpg');">
    <h3 style="text-align:center; color:black;font-size:40px; color:white;font-weight:bold"> Quản Lý    </h3>
    <h5 style="text-align:center; color:black;font-size:40px; color:white;font-weight:bold"> Đăng Nhập</h5>
    <h4 style="color:red; text-align:center">@ViewBag.ThongBao </h4>
    <br />
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <div class="wrap" style="font-style:italic;font-size:20px; text-align:center;color:white">
            <form class="form-horizontal">
                <div class="form-group">
                    <label class="control-label col-sm-2 text-white text-center" style="font-weight:bold;font-size:20px">Tài khoản:</label>
                    <div class="col-sm-12">
                        <input type="text" autocomplete="off" required class="form-control" name="TaiKhoan" style="text-align:center;height:30px;font-size:20px">
                    </div>
                    <label class="control-label col-sm-2 text-white text-center" style="font-weight:bold;font-size:20px">Mật khẩu:</label>
                    <div class="col-sm-12">
                        <input type="password" autocomplete="off" required class="form-control" name="MatKhau" style="text-align:center;height:30px;font-size:20px">
                    </div>
                </div><br />
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-12">
                        <button type="submit" class="btn btn-primary" style="border-color: chocolate;border-style: solid;border-radius: 15px;font-size:40px; margin:0 auto;display: flex">Vào</button>
                    </div>
                </div>
            </form>
        </div><br />
    }
</body>
</html>

Z9TheCoffee/Z9TheCoffee/Views/QuanLy_Z9TheCoffee/DanhSachChiNhanh.cshtml
@model IEnumerable<Z9TheCoffee.Models.ChiNhanh>

@{
    ViewBag.Title = "DanhSachChiNhanh";
    Layout = "~/Views/Shared/_LayoutQuanLy.cshtml";
}

<h2>Danh Sach Chi Nhanh</h2>

<p>
    @Html.ActionLink("Them moi", "ThemMoiChiNhanh")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenChiNhanh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TrangThai)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TenChiNhanh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TrangThai)
        </td>
        <td>
            @Html.ActionLink("Chỉnh Sửa", "SuaThongTinChiNhanh", new { id=item.MaChiNhanh })
        </td>
    </tr>
}

</table>

Z9TheCoffee/Z9TheCoffee/Views/QuanLy_Z9TheCoffee/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutQuanLy.cshtml";
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Trang Chủ
    </h1>
    <img src="~/img/rsz_picture4.png" />
</section>

Z9TheCoffee/Z9TheCoffee/Views/QuanLy_Z9TheCoffee/Menu.cshtml
@using Z9TheCoffee.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<Z9TheCoffee.Models.listMenu>
@{
    ViewBag.Title = "Quản Lý Menu";
    Layout = "~/Views/Shared/_LayoutQuanLy.cshtml";
}
<style>
    .zoom {
        transition: transform 1.2s;
    }

        .zoom:hover {
            -ms-transform: scale(2,2); /* IE 9 */
            -webkit-transform: scale(2,2); /* Safari 3-8 */
            transform: scale(2);
        }

    table {
        border-collapse: collapse;
        border-spacing: 0;
        width: 100%;
        border: 1px solid #ddd;
        text-align: center;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>
<br />
@Html.ActionLink("Xem Trang Chủ","Index","Z9TheCoffee",new { target = "_blank" })
<h2>Thông Tin Sản Phẩm</h2>
<div style="overflow-x:auto;">
    <table style="text-align:center" class="table responsive wrap" border="1">
        <tr style="text-align:center; font-weight:bold">
            <td>Ngày Cập Nhật</td>
            <td>Tên Loại</td>
            <td>Mã Sản Phẩm</td>
            <td>Tên</td>
            <td>Giá</td>
            <td>Ảnh</td>
            <td>Trạng Thái</td>
            <td>Tùy Chọn</td>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @String.Format("{0:dd/MM/yyyy}", item.NgayCapNhat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenLoai)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaDoUong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenDoUong)
                </td>
                <td>
                    @String.Format("{0:0,0}", item.GiaBan) VNĐ
                </td>
                <td>
                    <img src="@Url.Content("~/HinhSanPham/" + item.AnhBia)" width="50" height="60" class="zoom" />
                </td>
                <td>@Html.CheckBoxFor(modelItem => item.TrangThai)</td>
                <td>
                    @Html.ActionLink("Cập nhật", "CapNhatMenu", new { id = item.MaDoUong })
                </td>
            </tr>
        }
    </table>
</div>
<!--Tao lien ket các trang-->
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Menu", new { page = page }))
    <p style="font-size:20px">Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount</p>
</div>
<style>
    .MenuTrang li {
        color: white;
        float: left;
        padding: 8px 16px;
        text-decoration: none;
        transition: background-color .3s;
        border: 0.5px solid;
        font-size: 18px;
</style>

Z9TheCoffee/Z9TheCoffee/Views/QuanLy_Z9TheCoffee/SuaThongTinChiNhanh.cshtml
@model Z9TheCoffee.Models.ChiNhanh

@{
    ViewBag.Title = "SuaThongTinChiNhanh";
    Layout = "~/Views/Shared/_LayoutQuanLy.cshtml";
}

<h2>SuaThongTinChiNhanh</h2>

@using (Html.BeginForm("SuaThongTinChiNhanh", "QuanLy_Z9TheCoffee", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ChiNhanh</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaChiNhanh)

        <div class="form-group">
            @Html.LabelFor(model => model.TenChiNhanh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenChiNhanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenChiNhanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Z9TheCoffee/Z9TheCoffee/Views/QuanLy_Z9TheCoffee/ThemMoiChiNhanh.cshtml
@model Z9TheCoffee.Models.ChiNhanh

@{
    ViewBag.Title = "ThemMoiChiNhanh";
    Layout = "~/Views/Shared/_LayoutQuanLy.cshtml";
}

<h2>ThemMoiChiNhanh</h2>

@using (Html.BeginForm("ThemMoiChiNhanh","QuanLy_Z9TheCoffee", FormMethod.Post, new { @enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ChiNhanh</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenChiNhanh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenChiNhanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenChiNhanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Z9TheCoffee/Z9TheCoffee/Views/QuanLy_Z9TheCoffee/ThemMoiMenu.cshtml
@model Z9TheCoffee.Models.ChiTietDoUong

@{
    ViewBag.Title = "CapNhatMenu";
    Layout = "~/Views/Shared/_LayoutQuanLy.cshtml";
}
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cập nhật Menu</title>
    <style>
        table {
            border-collapse: collapse;
            border-spacing: 0;
            width: 100%;
            border: 1px solid #ddd;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    @using (Html.BeginForm("ThemMoiMenu", "QuanLy_Z9TheCoffee", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div style="overflow-x:auto;">
            <table style="border:solid;text-align:center" class="responsive wrap">
                <tr style="text-align:center; font-weight:bold;border:solid">
                    <td>Ngày Cập Nhật</td>
                    <td>Tên Loại</td>
                    <td>Tên Đồ Uống</td>
                    <td>Giá Bán</td>
                    <td>Ảnh Bìa</td>
                    <td>Trạng Thái</td>
                </tr>
                <tr style="text-align:center; font-weight:bold;border:solid">
                    <td style="border:solid;width:80px">
                        <input type="date" required name="NgayCapNhat" />
                    </td>
                    <td style="border:solid">@Html.DropDownList("MaLoai", ViewBag.MaLoai as SelectList)</td>
                    <td style="border:solid">
                        @Html.EditorFor(model => model.TenDoUong, new { htmlAttributes = new { @class = "form-control" ,@required = "required"} })
                        @Html.ValidationMessageFor(model => model.TenDoUong, "", new { @class = "text-danger" })
                    </td>
                    <td style="border:solid;width:90px">
                        @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                        @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
                    </td>
                    <td style="border:solid;width:60px">                        
                        <input type="file" name="fileUpload" />
                    </td>
                    <td style="border:solid;width:100px">
                        @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                    </td>
                </tr>
            </table><br />
            <div style="text-align: center"><button class="btn primary-btn" type="submit">Thêm</button></div>
        </div>
    }
</body>